### ISSUE TITLE
端口号

### ISSUE THREAD

**Issue by EdisonGates** [KwokRoot/api-mock-server#1]
开发者你好，请问是否可以更改成默认80口，我用反向代理后出现无法返回json的问题。谢谢！

**Comment by KwokRoot** [comment]
考虑到Apache、Nginx 等代理工具一般使用 80 端口，固不使用 80 端口。反向代理可以代理到其他 IP 的其他端口。根据你的使用情况，如果本程序默认使用80端口，会造成本程序直接启动失败(端口占用)，给使用者造成不便，谢谢你的关注。

**Comment by KwokRoot** [comment]
@EdisonGates 
考虑到Apache、Nginx 等代理工具一般使用 80 端口，固不使用 80 端口。反向代理可以代理到其他 IP 的其他端口。根据你的使用情况，如果本程序默认使用80端口，会造成本程序直接启动失败(端口占用)，给使用者造成不便，谢谢你的关注。

**Comment by EdisonGates** [comment]
> @EdisonGates
> 考虑到Apache、Nginx 等代理工具一般使用 80 端口，固不使用 80 端口。反向代理可以代理到其他 IP 的其他端口。根据你的使用情况，如果本程序默认使用80端口，会造成本程序直接启动失败(端口占用)，给使用者造成不便，谢谢你的关注。

已自编译解决，谢谢解答！
